FROM tomcat:11-jre25-temurin
MAINTAINER "FIZ-Karlsruhe"

ARG UNAME=oai_provider
ARG UID=8008
ARG GID=8008

RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

RUN chown -R ${UNAME}:${UNAME} /usr/local/tomcat/
RUN chmod -R 770 /usr/local/tomcat/

RUN export JAVA_OPTS="$JAVA_OPTS -Dlog4j2.formatMsgNoLookups=true"

#Log X-Forwarded-For
RUN sed -i 's/pattern="%h %l %u %t &quot;%r&quot; %s %b"/pattern="%{X-Forwarded-For}i %l %u %t \&quot;%r\&quot; %s %b"/' \
    /usr/local/tomcat/conf/server.xml

# --- Harden Tomcat error pages ---
# Add ErrorReportValve under <Host> to prevent stack traces and server info leakage
# (idempotent: only inserts if not already present)
RUN grep -q 'org.apache.catalina.valves.ErrorReportValve' /usr/local/tomcat/conf/server.xml \
 || sed -i 's#</Host>#  <!-- Prevent Tomcat from showing stack traces and server info on error pages -->\n  <Valve className="org.apache.catalina.valves.ErrorReportValve" showReport="false" showServerInfo="false"/>\n</Host>#' /usr/local/tomcat/conf/server.xml


USER $UNAME

COPY target/oai.war /usr/local/tomcat/webapps