FROM tomcat:9-jre11-openjdk-slim
MAINTAINER "FIZ-Karlsruhe"

ARG UNAME=oai_provider
ARG UID=8008
ARG GID=8008

#ARG UNAME=admin
#ARG UID=1000
#ARG GID=1000

RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

RUN chown -R ${UNAME}:${UNAME} /usr/local/tomcat/
RUN chmod -R 770 /usr/local/tomcat/

RUN export JAVA_OPTS="$JAVA_OPTS -Dlog4j2.formatMsgNoLookups=true"

USER $UNAME

COPY target/oai.war /usr/local/tomcat/webapps